const { Schema, model } = require('mongoose')

const mfwpSchema = new Schema({
  DW_SK_WP: Number,
  NPWP: { type: String, index: true },
  REGWP: String,
  KPPADM: { type: String, index: true },
  ID_JNS_WP: Number,
  ID_STS_PUSAT: Number,
  NPWP_PUSAT: String,
  NAMA_WP: String,
  JALAN: String,
  BLOK: String,
  NOMOR: String,
  RT: String,
  RW: String,
  KD_WIL: String,
  TELP: String,
  FAX: String,
  HP: String,
  EMAIL: String,
  KD_KLU: String,
  ID_KATEGORI: Number,
  FG_PKP: Number,
  FG_PPH42: Number,
  FG_PPH15: Number,
  FG_PPH19: Number,
  FG_PPH21: Number,
  FG_PPH22: Number,
  FG_PPH23: Number,
  FG_PPH25: Number,
  FG_PPH25OPPT: Number,
  FG_PPH26: Number,
  FG_PPH29: Number,
  FG_PPHFINAL: Number,
  FG_PPNKMS: Number,
  FG_PPNBM: Number,
  FG_PUT: Number,
  FG_PPN: Number,
  TGL_DAFTAR: Date,
  TGL_PKP: Date,
  TGL_PINDAH: Date,
  ID_STS_WP: Number,
  KD_FRM: String,
  NO_TRX: String,
  ID_JNS_PMH: Number,
  KD_VIP: String,
  KD_NOTE: String,
  ID_JNS_TRX: Number,
  VALID_TGL: Date,
  VALID_NIP: String,
  ID_SBR_DATA: Number,
  NIP_AR: { type: String, index: true },
  NIP_JS: String,
  DW_PROCESS_DATE: Date,
  THN_DAFTAR: { type: String, index: true },
})

module.exports = model('MFWP', mfwpSchema, 'MFWP')