const { model, Schema } = require('mongoose')

const mfwpSchema = new Schema({
  KD_KPP: { type: String, index: true },
  NPWP: { type: String, index: true, unique: true },
  NAMA_WP: { type: String, index: true },
  JENIS_WP: { type: String, index: true },
  ALAMAT: String,
  KELURAHAN: String,
  KECAMATAN: String,
  KOTA: String,
  PROVINSI: String,
  TELP: String,
  EMAIL: String,
  NIK: String,
  ID_REGISTER: String,
  TGL_DAFTAR: String,
  BLN_DAFTAR: String,
  THN_DAFTAR: { type: String, index: true },
  STATUS_WP: String,
  TEMPAT_LAHIR: String,
  TGL_LAHIR: String,
  KD_SEKSI: { type: Number, index: true },
  NIP_AR: { type: String, index: true },
  NIP_ATASAN_AR: String,
  PENANGGUNGJAWAB: String,
  BADAN_HUKUM: String,
  STATUS_MODAL: String,
  STATUS_USAHA: String,
  KD_KLU: { type: String, index: true },
  STATUS_PKP: String,
  NO_PKP: String,
  TGL_PKP: String,
  NO_CABUT_PKP: String,
  TGL_CABUT_PKP: String,
  KEWAJIBAN: [String],
}, { timestamps: true })

module.exports = model('MFWP', mfwpSchema, 'MFWP')